{% set version = "2.0.0" %}

package:
  name: maison
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/maison/maison-{{ version }}.tar.gz
  sha256: f5dafbbf4ce57bdb7cae128e075f457434b2cc9573b4f4bb4535f16d2ebd1cc5

build:
  entry_points:
    - maison = maison.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - click
    - toml

test:
  imports:
    - maison
  commands:
    - pip check
    - maison --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbatten5/maison
  summary: Read settings from config files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
